### ISSUE TITLE
Extension counts in format radar charts and registry comparisons disagree

### ISSUE THREAD

**Issue by nkrabben** [digipres/digipres.github.io#15]
For example, radar chart for LC FDD says 235...
http://www.digipres.org/formats/sources/fdd/
...and the overlap chart sums up to >250
http://www.digipres.org/formats/overlaps/

It's not clear which count is accurate.

**Comment by anjackson** [comment]
IIRC, I thought at the time that showing the number of format entries that had one-or-more extensions made more sense (i.e. you could get a sense of whether the registry tried to get all properties for all formats, because ideally every format might have an extension & MIME type & magic (which would be a square plot).

However, looking at it now, it just seems rather confusing.

**Comment by anjackson** [comment]
To clarify, the radar chart shows the number of records that have a file extension, and the comparisons show the number of unique file extensions.  Many records have the same file extension (e.g. file versions), so this is why they appear to disagree.

I think it makes more sense to use the unique extension and MIME type counts everywhere.

**Comment by anjackson** [comment]
Okay, I think that's implemented properly now.
