### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by todrobbins** [digipres/digipres.github.io#4]
Any need for work on the existing site? I'll have a bit of time over the holidays to lend a hand.

Cheers! ❄️

**Comment by prwheatley** [comment]
Hey Tod, thanks for the offer of help!

On the digipres main page a bit of freshening up would be great. I think a couple of links need fixing, the OAIS Community and File format assessments (here http://wiki.dpconline.org/index.php?title=Main_Page) could be linked to. Otherwise, any other new communityish things could be added. The "Save digital stuff now" box is a bit sparse. Some of the recent Rhizome/Freiburg emulation stuff could be added perhaps? Webrecorder.io

Coptr is always in need of some love. Plenty of new tools to add in. The Ohloh/Openhub.net info boxes have stopped working, but that might be tricky to fix without input from Andy.

I'm not sure there's anything else more exciting...

There was an idea that came up the other day but it's probably the other end of the spectrum - a bit of a project.... It would funnel examples of file formats that weren't being identified (or identified correctly) into the OPF format corpus. It would begin perhaps with a submit button in repository software that would encourage submissions and then some sort of process in the format corpus that would queue up problem files for development of ID magic (perhaps with alerts for the file format geeks) and then queue them up for TNA for incorporation in next round of Pronom sigs. Relates a bit to the stuff we did on the curatecamp fileformatid hack: http://wiki.curatecamp.org/index.php/CURATEcamp_24_hour_worldwide_file_id_hackathon_Nov_16_2012

So obviously there's an engagement bit with repository vendors/dev, which it would be pretty dependent on, but that we could probably help with from the DPC end. But there's perhaps also some preparatory work that could be done at the format corpus end first. That turned into a bit of a brain dump, anyway a few ideas to set the ball rolling...

**Comment by anjackson** [comment]
I'd always hoped we could do more with the formats part, http://www.digipres.org/formats/, e.g. plot graphs of known formats over time, etc. I never finished the part that updated to the latest PRONOM signatures either. However, the code that updated the formats and tools parts (https://github.com/digipres/sentinel) is perhaps a bit over complicated, so might not be much fun to work on. Any ideas for better ways to do that kind of thing would be much appreciated.

As @prwheatley, linking to and describing http://oldweb.today/ would be good.

**Comment by todrobbins** [comment]
Looks like some good stuff to tackle. Let me look over it some more this evening and I'll come back with a game plan. @anjackson, do you want to collaborate on any of these?

**Comment by anjackson** [comment]
I'm afraid I'm flat out right now, so I'm not going to be much help. I can answer questions etc, but that's about it.

**Comment by todrobbins** [comment]
No problem. Thanks @anjackson.

**Comment by anjackson** [comment]
If you're still interested, I think the [new front page](https://github.com/digipres/digipres.github.io/blob/master/index.md) could use some editorial review? No worries if not.

**Comment by anjackson** [comment]
Superseded by #37
